### ISSUE TITLE
Textbox border not updating after theme change until clicked

### ISSUE THREAD

**Issue by melsawy93** [AvaloniaCommunity/Material.Avalonia#321] opened 2023-11-20 14:39 UTC
I have a textbox:
```
<TextBox
    Grid.Column="0"
    Width="225"
    VerticalAlignment="Center"
    p1:TextFieldAssist.Label="Search Tools"
    Classes="solo dense clearButton"
    Text="{Binding SearchText, Mode=TwoWay}"
    Theme="{StaticResource OutlineTextBox}" />
```

I have a button to flip the theme of my app via:

```
public void ToggleBaseThemeMode()
{
    if (_isLightTheme)
    {
        // Switch to Dark Theme
        Theme theme = Theme.Create(Theme.Dark, _primaryColor, SwatchHelper.Lookup[(MaterialColor)SecondaryColor.Lime]);
        _materialThemeBase.CurrentTheme = theme;
    }
    else
    {
        // Switch to Light Theme
        Theme theme = Theme.Create(Theme.Light, _primaryColor, SwatchHelper.Lookup[(MaterialColor)SecondaryColor.Lime]);
        _materialThemeBase.CurrentTheme = theme;
    }

    _isLightTheme = !_isLightTheme; // Toggle the theme state
}
```

I have noticed when flipping the theme, the borderbrush of my textbox doesnt get changed until I "click" into the textbox and it somehow refreshes? Is there someway to force it to change? See gif below:
![Animation](https://github.com/AvaloniaCommunity/Material.Avalonia/assets/49313258/dc12e2f0-73f3-4282-b80e-12ede6038be1)

**Comment by SKProCH** [comment] 2023-11-20 15:20
This is issue on Avalonia side.

Also, duplicate of https://github.com/AvaloniaCommunity/Material.Avalonia/issues/262

**Closed by SKProCH** 2023-11-20 15:20 UTC

**Comment by melsawy93** [comment] 2023-11-20 15:23
Thanks, I missed the original issue, are you aware of any workaround? I will follow up with the issue on the avalonia side that you have opened.

**Comment by SKProCH** [comment] 2023-11-20 22:00
I was thinking about removing and re-adding the necessary brushes that are used in the TextBox when the theme changes. I assume that this should be done in the MaterialTheme/MaterialThemeBase class. I did a similar workaround for a similar bug some time ago. 

If you experiment, please let me know the results. I'm also planning to do some tests on this, but I'm not sure when I'll have free time to do it.

**Comment by melsawy93** [comment] 2023-11-20 22:12
> I was thinking about removing and re-adding the necessary brushes that are used in the TextBox when the theme changes. I assume that this should be done in the MaterialTheme/MaterialThemeBase class. I did a similar workaround for a similar bug some time ago.
> 
> If you experiment, please let me know the results. I'm also planning to do some tests on this, but I'm not sure when I'll have free time to do it.

Happy to look further into this, but I need to make sure I understand you correctly as this is all new to me. Are you saying when setting the theme in MaterialThemeBase, I should also look at which brushes inside the materialThemebase and re-assign them?

**Comment by SKProCH** [comment] 2023-11-20 22:48
Yep. You can also look to commit history of these files and you should find the required code.
