### ISSUE TITLE
Changing Theme Doesn't Update Textbox, Combobox, and DatePicker Line Colors

### ISSUE THREAD

**Issue by seikosantana** [AvaloniaCommunity/Material.Avalonia#308] opened 2023-10-27 02:59 UTC
I implemented dark/light mode toggle on the application. When theme mode is changed, most colors change but Textbox line colors don't, until I hover on the Textbox.

Before toggle:
![image](https://github.com/AvaloniaCommunity/Material.Avalonia/assets/35630407/0487aa53-2b75-485f-aa58-683d606a2ee5)

After toggle:
![image](https://github.com/AvaloniaCommunity/Material.Avalonia/assets/35630407/0af4adc5-8a0a-473d-9e9e-9394771f387a)

After hovering the TextBox (the bottom one)
![image](https://github.com/AvaloniaCommunity/Material.Avalonia/assets/35630407/06d7b5c6-1880-49fb-a484-4530294cb08b)

Here's how I toggled the theme:
```cs
var themeBootstrap = app.LocateMaterialTheme<MaterialTheme>();
themeBootstrap.BaseTheme = DarkModeSwitch.IsChecked ?? false ? BaseThemeMode.Dark : BaseThemeMode.Light;
```

Am I not toggling the theme correctly?

Thanks in advance

**Comment by seikosantana** [comment] 2023-10-27 03:15
I found that it also happens to Comboboxes

After Toggle
![image](https://github.com/AvaloniaCommunity/Material.Avalonia/assets/35630407/a48f9a2e-f5de-4b1e-8189-aa58a40cec30)

Same effects, colors are adjusted after hover

**Comment by seikosantana** [comment] 2023-10-27 03:19
It seems to also affect DatePickers

**Comment by SKProCH** [comment] 2023-10-27 07:08
Duplicate of #262

**Closed** 2023-10-27 07:08 UTC
