### ISSUE TITLE
ComboBox items not shown with left click on MacOS

### ISSUE THREAD

**Issue by mjuen** [AvaloniaCommunity/Material.Avalonia#128] opened 2021-12-05 16:23 UTC
Hello,

when using `Material.Avalonia` on Mac OS the `ComboBox` does not seems to work as expected. Left clicking does not reveal the available `ComboBoxItems`. The items are only shown when right clicking on the box. 

Versions:
```
Target framework: NET 5
Avalonia: 0.10.10
Avalonia.Desktop: 0.10.10
Avalonia.ReactiveUI: 0.10.10
Material.Avalonia: 2.5.0

Mac OS: Monterey 12.0.1
```

I have attached a solution to replicate the problem ([ComboBoxBug.zip](https://github.com/AvaloniaCommunity/Material.Avalonia/files/7656342/ComboBoxBug.zip)).

Steps to reproduce:

* Download the attached solution and publish the project with the following settings:

![publish](https://user-images.githubusercontent.com/7404431/144754533-32fd4216-8d7e-48e6-b114-5b7c65074a8f.png)

* Run the program on MacOS and click on the `ComboBox`

Expected behavior: 
`ComboBoxItems` are shown when left clicking on the `ComboBox`

Actual behavior:
`ComboBoxItems` are not shown when left clicking on the `ComboBox`, right clicks however seem to work

**Comment by SKProCH** [comment] 2021-12-05 18:25
Hello, @mjuen 
Does this reproducible without Material.Avalonia (on default avalonia theme)? 
Does this reproducible on other platforms?

**Comment by mjuen** [comment] 2021-12-05 19:36
Hi @SKProCH,

it works on MacOS without `Material.Avalonia` and the default Avalonia styles. In Windows it works fine with and without `Material.Avalonia`.

**Comment by jamsoft** [comment] 2022-06-08 12:04
I'm just using the FluentTheme and I cannot get any ComboBox dropdown to appear at all on OSX.

Left, middle or right clicking.

**Comment by DirkKramer** [comment] 2023-11-17 10:10
Same issue on Linux Ubuntu 20.04.  I can open the combobox using the keyboard, but not with left click.

**Comment by SKProCH** [comment] 2023-11-17 12:48
> Same issue on Linux Ubuntu 20.04.  I can open the combobox using the keyboard, but not with left click.

Hello. Can you attach a minimal reproduceable example project, please?  
Also please make sure  that problem also occurs on the default Avalonia theme.

**Comment by DirkKramer** [comment] 2023-11-17 13:23
> > Same issue on Linux Ubuntu 20.04.  I can open the combobox using the keyboard, but not with left click.
> 
> Hello. Can you attach a minimal reproduceable example project, please? Also please make sure that problem also occurs on the default Avalonia theme.

Problem is different on Default Avalonia. 

see below repo.
https://github.com/DirkKramer/ComboboxIssue

**Comment by SKProCH** [comment] 2023-11-18 23:45
@DirkKramer, seems like i can't reproduce it: 

https://github.com/AvaloniaCommunity/Material.Avalonia/assets/29896317/c68bd16e-7634-4e7b-bd2c-6271a5ff5688

**Comment by henrrymoraes83** [comment] 2024-01-22 22:50
I have the same  issue using Avalonia 11.0.7 on Mac OS 14.2.1 (23C71). Both latest version.

**Comment by SKProCH** [comment] 2024-05-13 21:14
Closing as bug on Avalonia's side. Track progress here: 

https://github.com/AvaloniaUI/Avalonia/issues/12383

**Closed by SKProCH** 2024-05-13 21:14 UTC
Labels: bug
